openapi: 3.0.0
info:
  title: lambda-typescript-express-sequelize-jest
  description: ducumentacion de lambda-typescript-express-sequelize-jest
  version: 1.0.0
  servers:
    - http://localhost:4000
paths: ''
components:
  parameters: ''
  definitions: ''
  schemas:
    User:
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal usuario
          example: '3973'
        primerNombre:
          type: string
          required: true
          description: Primer nombre del usuario
          example: '3973'
        sub:
          type: string
          required: false
          description: Id de usuario de Cognito aws
          example: '3973'
    Supplier:
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal proveedor
          example: '3973'
        descripcion:
          type: string
          required: false
          description: descripcion del proveedor
          example: '3973'
        empresa:
          type: string
          required: true
          description: nombre de empresa del proveedor
          example: '3973'
        equipo:
          type: string
          required: false
          example: '3973'
        fechaInicio:
          type: string
          required: true
          example: '3973'
        horaInicio:
          type: string
          required: true
          example: '3973'
        fechaHoraFin:
          type: string
          required: false
          example: '3973'
        activo:
          type: string
          required: true
          example: '3973'
  tags: ''
