openapi: 3.0.0
info:
  title: lambda-typescript-express-sequelizeipt
  description: ducumentacion de la api tablero de incidentes
  version: 1.0.0
  servers:
    - http://localhost:4000
paths:
  /api/User/all:
    get:
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/User'
  /api/User/add:
    post:
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/User'
  /api/Supplier/all:
    get:
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Supplier'
  /api/Supplier/add:
    post:
      summary: null
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Supplier'
components:
  parameters: ''
  definitions:
    User:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal usuario
          example: '3973'
        primerNombre:
          type: string
          required: true
          description: Primer nombre del usuario
          example: '3973'
        sub:
          type: string
          required: false
          description: Id de usuario de Cognito aws
          example: '3973'
    Supplier:
      type: object
      properties:
        uuid:
          type: string
          required: true
          description: identificador universal unico para la tabal proveedor
          example: '3973'
        empresa:
          type: string
          required: true
          description: nombre de empresa del proveedor
          example: '3973'
        equipo:
          type: number
          required: false
          description: proveedor equipo
          example: '3973'
        fechaInicio:
          type: string
          required: true
          description: proveedor fecha inicio
          example: '3973'
        horaInicio:
          type: string
          required: true
          description: proveedor hora inicio
          example: '3973'
        fechaHoraFin:
          type: string
          required: false
          description: proveedor fecha hora fin
          example: '3973'
        descripcion:
          type: string
          required: false
          description: descripcion del proveedor
          example: '3973'
        activo:
          type: boolean
          required: true
          description: proveedor activo
          example: '3973'
  schemas:
    User:
      allOf:
        - $ref: '#/components/definitions/User'
    Supplier:
      allOf:
        - $ref: '#/components/definitions/Supplier'
  tags: ''
